language: scala
dist: xenial
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test it:test
scala:
  - 2.13.3
  - 2.12.11
jdk:
  - oraclejdk11
  - openjdk11
  - openjdk8
notifications:
  email:
    - martins@uniso.lv
